### ISSUE TITLE
[Server] Enrollment는 클라이언트의 수강 자격을 검증합니다

### ISSUE THREAD

**Issue by yeahjinjeong** [ssg-java3-240304/oop2-oops-enrollment#10]
## 🌈 Success criteria 

1. 상세설명
2. 

## 👷To-do

- [x] [수강신청기간 체크] 시스템의 현재 시간과 수강신청기간을 비교합니다.
- [x] [수강가능한 학점 체크] (Student객체의 totalCredits + 해당 Course의 credit)가 18학점보다 작거나 같은지 확인합니다.
- [x] [전공 체크] Student객체의 major와 해당 Course의 major비교합니다.
- [x] [선수과목 체크]Student객체의 enrolledCourses중 해당 Course객체의 prerequisite의 id와 같은 key id가 있는지 검증
- [x] [정원체크] 해당 Course의 currentCapacity와 capacity 비교
