### ISSUE TITLE
[Server] Enrollment는 Controller로부터 매개변수로 전달받은 클라이언트의 학번과 수강신청과목코드를 통해 해당 학생의 Student 객체와 Course 객체에 수강신청과목을 추가할 수 있습니다.

### ISSUE THREAD

**Issue by yeahjinjeong** [ssg-java3-240304/oop2-oops-enrollment#11]
## 🌈 Success criteria 

1. 상세설명
2. 

## 👷To-do

- [ ] totalCredits에 들으려는 Course의 credit + 연산
- [ ] EnrolledCourses에 수강신청한 Course객체 추가
- [ ] 해당 Course의 currentCapacity에 + 연산
