### ISSUE TITLE
[Server] Enrollment는 Controller로부터 매개변수로 전달받은 클라이언트의 학번과 수강철회할 과목코드를 통해 해당 학생의 객체에 저장된 수강신청과목을 삭제할 수 있습니다.

### ISSUE THREAD

**Issue by yeahjinjeong** [ssg-java3-240304/oop2-oops-enrollment#13]
## 🌈 Success criteria 

1. 상세설명
2. 

## 👷To-do

- [x] EnrolledCourses에 수강철회할 Course객체 id를 비교 조회하여 삭제하기
- [ ] totalCredits에 들으려는 Course의 credit - 연산
- [ ] 해당 Course의 currentCapacity에 - 연산
