### ISSUE TITLE
[Server] Controller는 클라이언트의 자격을 검증한 후 false값을 반환하거나, true일 시 클라이언트의 요청에 따라 응답합니다.

### ISSUE THREAD

**Issue by yeahjinjeong** [ssg-java3-240304/oop2-oops-enrollment#18]
## 🌈 Success criteria 

1. 상세설명
2. 

## 👷To-do

- [ ] Controller는 클라이언트가 수강신청 메뉴를 선택할 경우 수강신청 메소드를 실행시킵니다.
- [ ] Controller는 클라이언트가 수강철회 메뉴를 선택할 경우 수강철회 메소드를 실행시킵니다.
- [ ] Controller는 클라이언트가 수강신청과목조회 메뉴를 선택할 경우 수강신청과목조회 메소드를 실행시킵니다.
